# Coverage configuration for Rye package
# Handles both R code (via covr) and Rye code (via tools/coverage/rye-coverage.R)

# Output directory structure
output:
  base_dir: "coverage"
  r_dir: "coverage/r"
  rye_dir: "coverage/rye"
  combined_dir: "coverage/combined"

# R code coverage (via covr)
r_coverage:
  enabled: true
  type: "all"  # tests, vignettes, examples, all, none
  relative_path: true
  quiet: false

  # Output formats
  formats:
    - html       # coverage/r/index.html
    - json       # coverage/r/coverage.xml (cobertura format)
    - console    # terminal output

  # Line exclusions (by file pattern)
  line_exclusions: []

  # Function exclusions
  function_exclusions: []

  # Coverage thresholds
  thresholds:
    line: 80      # minimum line coverage percentage
    function: 75  # minimum function coverage percentage

# Rye code coverage (via tools/coverage/rye-coverage.R)
rye_coverage:
  enabled: true

  # Directories to scan for .rye files
  scan_dirs:
    - "inst/rye"
    - "tests/native"

  # Output formats
  formats:
    - html       # coverage/rye/index.html
    - json       # coverage/rye/coverage.json (codecov format)
    - console    # terminal output

  # File exclusions (glob patterns)
  exclusions:
    - "inst/rye/.rye_cache/*"

  # Coverage thresholds
  thresholds:
    line: 85      # minimum line coverage percentage

# Combined reporting
combined:
  enabled: true

  # Generate unified summary report
  summary: true

  # Output formats for combined report
  formats:
    - html       # coverage/combined/index.html
    - markdown   # coverage/combined/COVERAGE.md

# Codecov integration
codecov:
  enabled: true

  # Upload settings
  upload:
    r_coverage: true
    rye_coverage: true

  # Flags for separating coverage types
  flags:
    r: "r-code"
    rye: "rye-code"

  # Project-level settings (for codecov.yml)
  projects:
    r:
      target: 80%
      threshold: 2%
    rye:
      target: 85%
      threshold: 2%

# CI-specific settings
ci:
  fail_on_threshold: false  # Don't fail CI on threshold miss (for now)
  upload_artifacts: true    # Upload HTML reports as CI artifacts
  artifact_retention_days: 30
