# Coverage configuration for Arl package
# Handles both R code (via covr) and Arl code (via tools/coverage/arl-coverage.R)

# Output directory structure
output:
  base_dir: "coverage"
  r_dir: "coverage/r"
  arl_dir: "coverage/arl"
  combined_dir: "coverage/combined"

# R code coverage (via covr)
r_coverage:
  enabled: true
  type: "all"  # tests, vignettes, examples, all, none
  relative_path: true
  quiet: false

  # Output formats
  formats:
    - html       # coverage/r/index.html
    - json       # coverage/r/coverage.xml (cobertura format)
    - console    # terminal output

  # Line exclusions (by file pattern)
  line_exclusions: []

  # Function exclusions
  function_exclusions: []

  # Coverage thresholds
  thresholds:
    line: 80      # minimum line coverage percentage
    function: 75  # minimum function coverage percentage

# Arl code coverage (via tools/coverage/arl-coverage.R)
arl_coverage:
  enabled: true

  # Directories to scan for .arl files
  scan_dirs:
    - "inst/arl"
    - "tests/native"

  # Output formats
  formats:
    - html       # coverage/arl/index.html
    - json       # coverage/arl/coverage.json (codecov format)
    - console    # terminal output

  # File exclusions (glob patterns)
  exclusions:
    - "inst/arl/.arl_cache/*"

  # Coverage thresholds
  thresholds:
    line: 85      # minimum line coverage percentage

# Combined reporting
combined:
  enabled: true

  # Generate unified summary report
  summary: true

  # Output formats for combined report
  formats:
    - html       # coverage/combined/index.html
    - markdown   # coverage/combined/COVERAGE.md

# Codecov integration
codecov:
  enabled: true

  # Upload settings
  upload:
    r_coverage: true
    arl_coverage: true

  # Flags for separating coverage types
  flags:
    r: "r-code"
    arl: "arl-code"

  # Project-level settings (for codecov.yml)
  projects:
    r:
      target: 80%
      threshold: 2%
    arl:
      target: 85%
      threshold: 2%

# CI-specific settings
ci:
  fail_on_threshold: false  # Don't fail CI on threshold miss (for now)
  upload_artifacts: true    # Upload HTML reports as CI artifacts
  artifact_retention_days: 30
