window.BENCHMARK_DATA = {
  "lastUpdate": 1770857533724.33,
  "repoUrl": "https://github.com/wwbrannon/arl",
  "entries": {
    "Benchmark": [
      {
        "commit": {
          "author": {"username": "wwbrannon"},
          "committer": {"username": "wwbrannon"},
          "id": "d973525",
          "message": "first benchmark baseline",
          "timestamp": "2026-02-06T23:37:09Z",
          "url": "https://github.com/wwbrannon/arl/commit/d973525"
        },
        "date": 1738888554000,
        "tool": "customSmallerIsBetter",
        "benches": [
            {"name": "tokenizer/strings/10 chars", "unit": "ms", "value": 0.03321003},
            {"name": "tokenizer/strings/100 chars", "unit": "ms", "value": 0.2515555},
            {"name": "tokenizer/strings/1K chars", "unit": "ms", "value": 2.375786},
            {"name": "tokenizer/strings/10K chars", "unit": "ms", "value": 24.8986},
            {"name": "tokenizer/nested/10 levels", "unit": "ms", "value": 0.122631},
            {"name": "tokenizer/nested/50 levels", "unit": "ms", "value": 0.366212},
            {"name": "tokenizer/nested/100 levels", "unit": "ms", "value": 0.675393},
            {"name": "tokenizer/mixed/Small (3 exprs)", "unit": "ms", "value": 0.549564},
            {"name": "tokenizer/mixed/Medium (30 exprs)", "unit": "ms", "value": 5.561261},
            {"name": "tokenizer/mixed/Large (300 exprs)", "unit": "ms", "value": 51.73489},
            {"name": "tokenizer/escapes/No escapes", "unit": "ms", "value": 0.04108204},
            {"name": "tokenizer/escapes/Few escapes", "unit": "ms", "value": 0.04395214},
            {"name": "tokenizer/escapes/Many escapes", "unit": "ms", "value": 1.392873},
            {"name": "tokenizer/real/fibonacci.arl", "unit": "ms", "value": 22.59879},
            {"name": "tokenizer/real/quicksort.arl", "unit": "ms", "value": 26.95916},
            {"name": "tokenizer/real/macro-examples.arl", "unit": "ms", "value": 34.72926},
            {"name": "parser/flat/10 elements", "unit": "ms", "value": 0.136981},
            {"name": "parser/flat/100 elements", "unit": "ms", "value": 1.057636},
            {"name": "parser/flat/1000 elements", "unit": "ms", "value": 10.72324},
            {"name": "parser/nested/Depth 5", "unit": "ms", "value": 0.1559639},
            {"name": "parser/nested/Depth 10", "unit": "ms", "value": 0.2971475},
            {"name": "parser/nested/Depth 20", "unit": "ms", "value": 0.5923269},
            {"name": "parser/sugar/Single quote expr", "unit": "ms", "value": 0.187862},
            {"name": "parser/sugar/10 quote exprs", "unit": "ms", "value": 1.896742},
            {"name": "parser/nulls/Few NULLs", "unit": "ms", "value": 0.09844103},
            {"name": "parser/nulls/100 NULLs", "unit": "ms", "value": 1.159644},
            {"name": "parser/real/fibonacci.arl", "unit": "ms", "value": 6.966843},
            {"name": "parser/real/quicksort.arl", "unit": "ms", "value": 8.305944},
            {"name": "parser/real/macro-examples.arl", "unit": "ms", "value": 10.07099},
            {"name": "macro/simple/Simple macro", "unit": "ms", "value": 0.404465},
            {"name": "macro/complex/Complex macro", "unit": "ms", "value": 0.830824},
            {"name": "macro/nested/Nested macros", "unit": "ms", "value": 1.584671},
            {"name": "macro/hygiene/With hygiene", "unit": "ms", "value": 1.764046},
            {"name": "macro/heavy/Macro-heavy", "unit": "ms", "value": 11.65944},
            {"name": "macro/real/macro-examples.arl", "unit": "ms", "value": 506.294},
            {"name": "eval/arithmetic/Single add", "unit": "ms", "value": 0.3671141},
            {"name": "eval/arithmetic/Nested adds", "unit": "ms", "value": 0.785683},
            {"name": "eval/arithmetic/Many adds", "unit": "ms", "value": 2.073288},
            {"name": "eval/calls/1 arg", "unit": "ms", "value": 0.2924736},
            {"name": "eval/calls/5 args", "unit": "ms", "value": 0.6286325},
            {"name": "eval/calls/10 args", "unit": "ms", "value": 1.031478},
            {"name": "eval/special/if", "unit": "ms", "value": 0.4316275},
            {"name": "eval/special/define", "unit": "ms", "value": 0.5271779},
            {"name": "eval/special/lambda", "unit": "ms", "value": 0.6201661},
            {"name": "eval/special/begin", "unit": "ms", "value": 0.4367731},
            {"name": "eval/recursive/fibonacci(10)", "unit": "ms", "value": 4.18159},
            {"name": "eval/recursive/fibonacci(12)", "unit": "ms", "value": 9.667451},
            {"name": "eval/recursive/factorial(100)", "unit": "ms", "value": 2.673774},
            {"name": "eval/recursive/factorial(500)", "unit": "ms", "value": 12.82296},
            {"name": "eval/closures/Create closure", "unit": "ms", "value": 0.3451791},
            {"name": "eval/closures/Call closure", "unit": "ms", "value": 0.476625},
            {"name": "eval/real/fibonacci.arl", "unit": "ms", "value": 419.5007},
            {"name": "eval/real/quicksort.arl", "unit": "ms", "value": 496.0655},
            {"name": "stdlib/list_ops/car (10)", "unit": "ms", "value": 0.2890499},
            {"name": "stdlib/list_ops/cdr (10)", "unit": "ms", "value": 0.5854389},
            {"name": "stdlib/list_ops/length (10)", "unit": "ms", "value": 0.2807269},
            {"name": "stdlib/list_ops/length (100)", "unit": "ms", "value": 0.2836791},
            {"name": "stdlib/list_ops/length (1000)", "unit": "ms", "value": 0.2869589},
            {"name": "stdlib/list_ops/reverse (10)", "unit": "ms", "value": 0.3146339},
            {"name": "stdlib/list_ops/reverse (100)", "unit": "ms", "value": 0.4593231},
            {"name": "stdlib/higher_order/map (10)", "unit": "ms", "value": 0.491385},
            {"name": "stdlib/higher_order/map (100)", "unit": "ms", "value": 1.408043},
            {"name": "stdlib/higher_order/map (1000)", "unit": "ms", "value": 10.22312},
            {"name": "stdlib/higher_order/filter (10)", "unit": "ms", "value": 0.4531321},
            {"name": "stdlib/higher_order/filter (100)", "unit": "ms", "value": 1.089063},
            {"name": "stdlib/higher_order/reduce (10)", "unit": "ms", "value": 0.552188},
            {"name": "stdlib/higher_order/reduce (100)", "unit": "ms", "value": 1.265486},
            {"name": "stdlib/compose/Single function", "unit": "ms", "value": 0.2921046},
            {"name": "stdlib/compose/Two composed", "unit": "ms", "value": 0.4239605},
            {"name": "stdlib/compose/Three composed", "unit": "ms", "value": 0.552147},
            {"name": "stdlib/strings/str (2 args)", "unit": "ms", "value": 3.796621},
            {"name": "stdlib/strings/str (5 args)", "unit": "ms", "value": 8.862724},
            {"name": "stdlib/strings/str (10 args)", "unit": "ms", "value": 19.10426},
            {"name": "stdlib/predicates/null?", "unit": "ms", "value": 0.2789026},
            {"name": "stdlib/predicates/list?", "unit": "ms", "value": 0.5615565},
            {"name": "stdlib/predicates/number?", "unit": "ms", "value": 0.2879635},
            {"name": "stdlib/predicates/string?", "unit": "ms", "value": 0.249116},
            {"name": "stdlib/construction/cons (single)", "unit": "ms", "value": 0.581093},
            {"name": "stdlib/construction/append (2 lists)", "unit": "ms", "value": 1.9311},
            {"name": "stdlib/construction/append (large)", "unit": "ms", "value": 2.850484},
            {"name": "stdlib/construction/range (10)", "unit": "ms", "value": 0.5781821},
            {"name": "stdlib/construction/range (100)", "unit": "ms", "value": 0.725946},
            {"name": "stdlib/nested/map then filter", "unit": "ms", "value": 0.727996},
            {"name": "stdlib/nested/filter then map", "unit": "ms", "value": 0.6832241},
            {"name": "stdlib/nested/map, filter, reduce", "unit": "ms", "value": 1.064483},
            {"name": "interop/calls/mean positional", "unit": "ms", "value": 1.103925},
            {"name": "interop/calls/mean named", "unit": "ms", "value": 1.144412},
            {"name": "interop/calls/seq positional", "unit": "ms", "value": 0.477076},
            {"name": "interop/calls/seq named", "unit": "ms", "value": 0.5616795},
            {"name": "interop/objects/vector", "unit": "ms", "value": 0.9950289},
            {"name": "interop/objects/list", "unit": "ms", "value": 1.040375},
            {"name": "interop/objects/data.frame", "unit": "ms", "value": 1.140579},
            {"name": "interop/objects/formula", "unit": "ms", "value": 0.3717265},
            {"name": "modules/import/import binding", "unit": "ms", "value": 1314.776},
            {"name": "modules/import/import control", "unit": "ms", "value": 1310.824},
            {"name": "modules/load_run/load", "unit": "ms", "value": 1298.868},
            {"name": "modules/load_run/run", "unit": "ms", "value": 1324.567},
            {"name": "e2e/synthetic/Micro", "unit": "ms", "value": 1338.518},
            {"name": "e2e/synthetic/Small", "unit": "ms", "value": 1319.635},
            {"name": "e2e/synthetic/Medium", "unit": "ms", "value": 1389.525},
            {"name": "e2e/synthetic/Deep recursion", "unit": "ms", "value": 1338.353},
            {"name": "e2e/strings/1K string", "unit": "ms", "value": 1277.089},
            {"name": "e2e/strings/10K string", "unit": "ms", "value": 1333.116},
            {"name": "e2e/args/50 args", "unit": "ms", "value": 1280.531},
            {"name": "e2e/args/100 args", "unit": "ms", "value": 1289.522},
            {"name": "e2e/repl/REPL session", "unit": "ms", "value": 1271.755},
            {"name": "e2e/real/fibonacci.arl", "unit": "ms", "value": 1634.033},
            {"name": "e2e/real/quicksort.arl", "unit": "ms", "value": 1714.057},
            {"name": "e2e/real/macro-examples.arl", "unit": "ms", "value": 1726.341}
        ]
      },
      {
        "commit": {
          "author": {"username": "wwbrannon"},
          "committer": {"username": "wwbrannon"},
          "id": "effbe9f",
          "message": "second benchmark baseline",
          "timestamp": "2026-02-10T07:53:35Z",
          "url": "https://github.com/wwbrannon/arl/commit/effbe9f"
        },
        "date": 1739177613000,
        "tool": "customSmallerIsBetter",
        "benches": [
            {"name": "tokenizer/strings/10 chars", "unit": "ms", "value": 0.03521913},
            {"name": "tokenizer/strings/100 chars", "unit": "ms", "value": 0.05030702},
            {"name": "tokenizer/strings/1K chars", "unit": "ms", "value": 0.157563},
            {"name": "tokenizer/strings/10K chars", "unit": "ms", "value": 1.242177},
            {"name": "tokenizer/nested/10 levels", "unit": "ms", "value": 0.1043861},
            {"name": "tokenizer/nested/50 levels", "unit": "ms", "value": 0.2296818},
            {"name": "tokenizer/nested/100 levels", "unit": "ms", "value": 0.386466},
            {"name": "tokenizer/mixed/Small (3 exprs)", "unit": "ms", "value": 0.4475971},
            {"name": "tokenizer/mixed/Medium (30 exprs)", "unit": "ms", "value": 4.267977},
            {"name": "tokenizer/mixed/Large (300 exprs)", "unit": "ms", "value": 42.70047},
            {"name": "tokenizer/escapes/No escapes", "unit": "ms", "value": 0.03534206},
            {"name": "tokenizer/escapes/Few escapes", "unit": "ms", "value": 0.03591622},
            {"name": "tokenizer/escapes/Many escapes", "unit": "ms", "value": 0.09680097},
            {"name": "tokenizer/real/fibonacci.arl", "unit": "ms", "value": 14.68608},
            {"name": "tokenizer/real/quicksort.arl", "unit": "ms", "value": 18.43549},
            {"name": "tokenizer/real/macro-examples.arl", "unit": "ms", "value": 18.91785},
            {"name": "parser/flat/10 elements", "unit": "ms", "value": 0.1327579},
            {"name": "parser/flat/100 elements", "unit": "ms", "value": 1.041216},
            {"name": "parser/flat/1000 elements", "unit": "ms", "value": 10.39742},
            {"name": "parser/nested/Depth 5", "unit": "ms", "value": 0.151413},
            {"name": "parser/nested/Depth 10", "unit": "ms", "value": 0.2892551},
            {"name": "parser/nested/Depth 20", "unit": "ms", "value": 0.5716016},
            {"name": "parser/sugar/Single quote expr", "unit": "ms", "value": 0.1758081},
            {"name": "parser/sugar/10 quote exprs", "unit": "ms", "value": 1.734915},
            {"name": "parser/nulls/Few NULLs", "unit": "ms", "value": 0.09319303},
            {"name": "parser/nulls/100 NULLs", "unit": "ms", "value": 1.071248},
            {"name": "parser/real/fibonacci.arl", "unit": "ms", "value": 6.443724},
            {"name": "parser/real/quicksort.arl", "unit": "ms", "value": 7.864723},
            {"name": "parser/real/macro-examples.arl", "unit": "ms", "value": 9.225041},
            {"name": "macro/simple/Simple macro", "unit": "ms", "value": 0.4510002},
            {"name": "macro/complex/Complex macro", "unit": "ms", "value": 0.7974706},
            {"name": "macro/nested/Nested macros", "unit": "ms", "value": 1.638278},
            {"name": "macro/hygiene/With hygiene", "unit": "ms", "value": 1.17752},
            {"name": "macro/heavy/Macro-heavy", "unit": "ms", "value": 6.454302},
            {"name": "macro/real/macro-examples.arl", "unit": "ms", "value": 163.9165},
            {"name": "eval/arithmetic/Single add", "unit": "ms", "value": 0.3590985},
            {"name": "eval/arithmetic/Nested adds", "unit": "ms", "value": 0.7460361},
            {"name": "eval/arithmetic/Many adds", "unit": "ms", "value": 1.906459},
            {"name": "eval/calls/1 arg", "unit": "ms", "value": 0.28577},
            {"name": "eval/calls/5 args", "unit": "ms", "value": 0.5974111},
            {"name": "eval/calls/10 args", "unit": "ms", "value": 0.9791621},
            {"name": "eval/special/if", "unit": "ms", "value": 0.3490535},
            {"name": "eval/special/define", "unit": "ms", "value": 0.3486231},
            {"name": "eval/special/lambda", "unit": "ms", "value": 0.5734465},
            {"name": "eval/special/begin", "unit": "ms", "value": 0.3986021},
            {"name": "eval/recursive/fibonacci(10)", "unit": "ms", "value": 3.506566},
            {"name": "eval/recursive/fibonacci(12)", "unit": "ms", "value": 8.760634},
            {"name": "eval/recursive/factorial(100)", "unit": "ms", "value": 2.737324},
            {"name": "eval/recursive/factorial(500)", "unit": "ms", "value": 12.92367},
            {"name": "eval/closures/Create closure", "unit": "ms", "value": 0.216234},
            {"name": "eval/closures/Call closure", "unit": "ms", "value": 0.235914},
            {"name": "eval/real/fibonacci.arl", "unit": "ms", "value": 122.5692},
            {"name": "eval/real/quicksort.arl", "unit": "ms", "value": 155.4289},
            {"name": "stdlib/list_ops/car (10)", "unit": "ms", "value": 0.2788615},
            {"name": "stdlib/list_ops/cdr (10)", "unit": "ms", "value": 0.33661},
            {"name": "stdlib/list_ops/length (10)", "unit": "ms", "value": 0.2752126},
            {"name": "stdlib/list_ops/length (100)", "unit": "ms", "value": 0.2752536},
            {"name": "stdlib/list_ops/length (1000)", "unit": "ms", "value": 0.2789641},
            {"name": "stdlib/list_ops/reverse (10)", "unit": "ms", "value": 0.3010221},
            {"name": "stdlib/list_ops/reverse (100)", "unit": "ms", "value": 0.4450346},
            {"name": "stdlib/higher_order/map (10)", "unit": "ms", "value": 0.4564531},
            {"name": "stdlib/higher_order/map (100)", "unit": "ms", "value": 1.324608},
            {"name": "stdlib/higher_order/map (1000)", "unit": "ms", "value": 10.60311},
            {"name": "stdlib/higher_order/filter (10)", "unit": "ms", "value": 0.4442965},
            {"name": "stdlib/higher_order/filter (100)", "unit": "ms", "value": 1.165651},
            {"name": "stdlib/higher_order/reduce (10)", "unit": "ms", "value": 0.521807},
            {"name": "stdlib/higher_order/reduce (100)", "unit": "ms", "value": 1.263907},
            {"name": "stdlib/compose/Single function", "unit": "ms", "value": 0.2890909},
            {"name": "stdlib/compose/Two composed", "unit": "ms", "value": 0.4088725},
            {"name": "stdlib/compose/Three composed", "unit": "ms", "value": 0.5296995},
            {"name": "stdlib/strings/str (2 args)", "unit": "ms", "value": 0.679862},
            {"name": "stdlib/strings/str (5 args)", "unit": "ms", "value": 1.320856},
            {"name": "stdlib/strings/str (10 args)", "unit": "ms", "value": 2.370887},
            {"name": "stdlib/predicates/null?", "unit": "ms", "value": 0.219678},
            {"name": "stdlib/predicates/list?", "unit": "ms", "value": 0.5328769},
            {"name": "stdlib/predicates/number?", "unit": "ms", "value": 0.2698209},
            {"name": "stdlib/predicates/string?", "unit": "ms", "value": 0.2368982},
            {"name": "stdlib/construction/cons (single)", "unit": "ms", "value": 0.5385759},
            {"name": "stdlib/construction/append (2 lists)", "unit": "ms", "value": 0.868954},
            {"name": "stdlib/construction/append (large)", "unit": "ms", "value": 1.149804},
            {"name": "stdlib/construction/range (10)", "unit": "ms", "value": 0.4245141},
            {"name": "stdlib/construction/range (100)", "unit": "ms", "value": 0.5730775},
            {"name": "stdlib/nested/map then filter", "unit": "ms", "value": 0.700444},
            {"name": "stdlib/nested/filter then map", "unit": "ms", "value": 0.664774},
            {"name": "stdlib/nested/map, filter, reduce", "unit": "ms", "value": 1.012516},
            {"name": "interop/calls/mean positional", "unit": "ms", "value": 1.05165},
            {"name": "interop/calls/mean named", "unit": "ms", "value": 1.078054},
            {"name": "interop/calls/seq positional", "unit": "ms", "value": 0.464407},
            {"name": "interop/calls/seq named", "unit": "ms", "value": 0.5241851},
            {"name": "interop/objects/vector", "unit": "ms", "value": 0.936399},
            {"name": "interop/objects/list", "unit": "ms", "value": 0.9574934},
            {"name": "interop/objects/data.frame", "unit": "ms", "value": 1.038386},
            {"name": "interop/objects/formula", "unit": "ms", "value": 0.3497916},
            {"name": "modules/import/import binding", "unit": "ms", "value": 82.29299},
            {"name": "modules/import/import control", "unit": "ms", "value": 77.85701},
            {"name": "modules/load_run/load", "unit": "ms", "value": 80.61578},
            {"name": "modules/load_run/run", "unit": "ms", "value": 79.46366},
            {"name": "e2e/synthetic/Micro", "unit": "ms", "value": 83.09599},
            {"name": "e2e/synthetic/Small", "unit": "ms", "value": 83.29316},
            {"name": "e2e/synthetic/Medium", "unit": "ms", "value": 117.1897},
            {"name": "e2e/synthetic/Deep recursion", "unit": "ms", "value": 96.60463},
            {"name": "e2e/strings/1K string", "unit": "ms", "value": 76.87176},
            {"name": "e2e/strings/10K string", "unit": "ms", "value": 79.61944},
            {"name": "e2e/args/50 args", "unit": "ms", "value": 79.37612},
            {"name": "e2e/args/100 args", "unit": "ms", "value": 88.10787},
            {"name": "e2e/repl/REPL session", "unit": "ms", "value": 79.95223},
            {"name": "e2e/real/fibonacci.arl", "unit": "ms", "value": 204.1272},
            {"name": "e2e/real/quicksort.arl", "unit": "ms", "value": 254.4768},
            {"name": "e2e/real/macro-examples.arl", "unit": "ms", "value": 228.1942}
        ]
      }
    ]
  }
}

